# Generated by Django 3.2 on 2021-04-27 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactdb', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='image',
            field=models.URLField(max_length=1000, null=True),
        ),
    ]
